# Generated by Django 3.2.11 on 2022-01-25 09:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='numberoffollowers',
            field=models.PositiveBigIntegerField(default=0, verbose_name='numberoffollowers'),
        ),
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_date', models.DateTimeField()),
                ('feed_status', models.PositiveIntegerField(choices=[(1, 'registered'), (2, 'logged in'), (3, 'followed'), (4, 'unfollowed'), (5, 'created an event'), (6, 'created a service'), (7, 'applied service'), (8, 'applied event'), (9, 'confirmed')])),
                ('feed_event', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feed_event', to='authenticate.event')),
                ('feed_service', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feed_service', to='authenticate.service')),
                ('feed_user', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feed_user', to=settings.AUTH_USER_MODEL)),
                ('feed_user2', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feed_user2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
