# Generated by Django 4.0 on 2022-01-07 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Service Name')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Service Date')),
                ('description', models.TextField()),
                ('number_of_attendees', models.IntegerField()),
                ('provider', models.TextField()),
                ('attendees', models.ManyToManyField(blank=True, to='authenticate.MyClubUser')),
            ],
        ),
    ]
