# Generated by Django 3.2.11 on 2022-01-26 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0002_auto_20220126_1220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='body_commented',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='date_commented',
            new_name='datecomment',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='service_commented',
            new_name='service',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='user_commented',
            new_name='usercomment',
        ),
    ]
