# Generated by Django 3.2.11 on 2022-01-25 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0002_auto_20220125_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='feed_status',
            field=models.PositiveIntegerField(choices=[(1, 'registered'), (2, 'logged in'), (3, 'followed'), (4, 'unfollowed'), (5, 'created an event'), (6, 'created a service'), (7, 'applied service'), (8, 'applied event'), (9, 'confirmed'), (10, 'updated event')]),
        ),
    ]
