# Generated by Django 3.2.11 on 2022-01-08 05:46

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authenticate', '0003_event_venue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='number_of_attendees',
        ),
        migrations.RemoveField(
            model_name='myclubuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='myclubuser',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='myclubuser',
            name='username',
        ),
        migrations.AddField(
            model_name='event',
            name='applied_ones',
            field=models.ManyToManyField(blank=True, default='', related_name='event_applied_ones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='credit',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='others',
            field=models.ManyToManyField(blank=True, default='', null=True, related_name='event_others', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='service_picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Open'), (2, 'Closed'), (3, 'Done')], default=1),
        ),
        migrations.AddField(
            model_name='event',
            name='time',
            field=models.TimeField(default='12:00'),
        ),
        migrations.AddField(
            model_name='myclubuser',
            name='bio',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myclubuser',
            name='credit',
            field=models.PositiveBigIntegerField(default=5, validators=[django.core.validators.MaxValueValidator(15), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='myclubuser',
            name='onholdcredit',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(15), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='myclubuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='myclubuser',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='service',
            name='applied_ones',
            field=models.ManyToManyField(blank=True, default='', null=True, related_name='service_applied_ones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='service',
            name='others',
            field=models.ManyToManyField(blank=True, default='', related_name='service_others', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='service',
            name='service_picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='service',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Open'), (2, 'Closed'), (3, 'Done')], default=1),
        ),
        migrations.AddField(
            model_name='service',
            name='time',
            field=models.TimeField(default='12:00'),
        ),
        migrations.AlterField(
            model_name='event',
            name='attendees',
            field=models.ManyToManyField(blank=True, default='', related_name='event_attendees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Event Date'),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Event Name'),
        ),
        migrations.AlterField(
            model_name='event',
            name='provider',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='event_provider', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='service',
            name='attendees',
            field=models.ManyToManyField(blank=True, default='', related_name='service_attendees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='service',
            name='credit',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='service',
            name='provider',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='service_provider', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Final_Service_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_final_status', models.PositiveIntegerField(choices=[(1, 'Applied'), (2, 'Accepted'), (3, 'Completed'), (4, 'Not Completed'), (5, 'Rejected')])),
                ('service_final_status', models.ManyToManyField(default='', null=True, related_name='service_final_status', to='authenticate.Service')),
            ],
        ),
        migrations.CreateModel(
            name='Final_Event_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_final_status', models.PositiveIntegerField(choices=[(1, 'Applied'), (2, 'Accepted'), (3, 'Completed'), (4, 'Not Completed'), (5, 'Rejected')])),
                ('event_final_status', models.ManyToManyField(default='', null=True, related_name='event_final_status', to='authenticate.Service')),
            ],
        ),
    ]
