# Generated by Django 3.2.11 on 2022-01-26 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0004_auto_20220126_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='feed_status',
            field=models.PositiveIntegerField(choices=[(1, 'registered'), (2, 'logged in'), (3, 'followed'), (4, 'unfollowed'), (5, 'created an event'), (6, 'created a service'), (7, 'applied service'), (8, 'applied event'), (9, 'confirmed'), (10, 'updated event'), (11, 'deleted an event'), (12, 'edited profile information'), (13, 'updated service'), (14, 'deleted a service'), (15, 'canceled application'), (16, 'cancelled application to an event'), (17, 'confirmed event'), (18, 'commented on')]),
        ),
    ]
