# Generated by Django 3.2.11 on 2022-01-08 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0005_alter_myclubuser_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='venue',
            field=models.CharField(max_length=120, verbose_name='Venue Name'),
        ),
        migrations.AlterField(
            model_name='service',
            name='venue',
            field=models.CharField(max_length=120, verbose_name='Venue Name'),
        ),
        migrations.DeleteModel(
            name='Venue',
        ),
    ]
