# Generated by Django 3.2.11 on 2022-01-08 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authenticate', '0006_auto_20220108_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='applied_ones',
            field=models.ManyToManyField(default='', related_name='event_applied_ones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='others',
            field=models.ManyToManyField(blank=True, default='', related_name='event_others', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='provider',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_provider', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='final_event_status',
            name='event_final_status',
            field=models.ManyToManyField(default='', related_name='event_final_status', to='authenticate.Service'),
        ),
        migrations.AlterField(
            model_name='final_service_status',
            name='service_final_status',
            field=models.ManyToManyField(default='', related_name='service_final_status', to='authenticate.Service'),
        ),
        migrations.AlterField(
            model_name='service',
            name='applied_ones',
            field=models.ManyToManyField(blank=True, default='', related_name='service_applied_ones', to=settings.AUTH_USER_MODEL),
        ),
    ]
