# Generated by Django 3.2.11 on 2022-01-09 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0007_auto_20220108_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='owner',
            field=models.IntegerField(default=1, verbose_name='Service Owner'),
        ),
    ]
