# Generated by Django 4.0 on 2022-01-27 19:09

from django.db import migrations, models
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0008_remove_place_parent_place_place_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='cityname',
            field=models.CharField(default='Ankara', max_length=255),
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=location_field.models.plain.PlainLocationField(default='Ankara', max_length=63),
        ),
        migrations.AddField(
            model_name='service',
            name='cityname',
            field=models.CharField(default='Ankara', max_length=255),
        ),
        migrations.AddField(
            model_name='service',
            name='location',
            field=location_field.models.plain.PlainLocationField(default='Ankara', max_length=63),
        ),
    ]
