# Generated by Django 3.2.11 on 2022-01-10 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0009_event_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
