# Generated by Django 4.0.1 on 2022-01-29 09:18

from django.db import migrations
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0010_alter_event_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='venue',
        ),
        migrations.RemoveField(
            model_name='service',
            name='venue',
        ),
        migrations.AlterField(
            model_name='service',
            name='location',
            field=location_field.models.plain.PlainLocationField(max_length=63),
        ),
    ]
