# Generated by Django 4.0.1 on 2022-01-29 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0012_event_lat_event_lng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='lat',
            field=models.TextField(default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='lng',
            field=models.TextField(default=0),
        ),
    ]
