# Generated by Django 4.0.1 on 2022-01-29 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0013_alter_event_lat_alter_event_lng'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='event',
            name='lng',
        ),
    ]
